- lib/puppet/provider/firewall/iptables.rb
- spec/acceptance/resource_cmd_spec.rb
The parser was arbitrarily requiring `--(d|s)port` or `-m multiport` with
`-m tcp` or `-m udp`.
> MODULES-1552 - Issues parsing `-m (tcp|udp)` rules

- lib/puppet/provider/firewall/ip6tables.rb
- spec/acceptance/firewall_spec.rb
README and provider already claimed ip6tables provider supported `mark`
feature, but the code wasn't there.
Fixes puppetlabs/puppetlabs-firewall#387
> MODULES-1612 - sync set_mark

- README.markdown
- lib/puppet/provider/firewall/ip6tables.rb
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_bridging_spec.rb
Added support for iptables physdev_in and physdev_out parameters. This allows puppet to mange firewall rules in bridged environments.
> Added support for iptables physdev_in and physdev_out parameters

- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_uid_spec.rb
Fix for MODULES-1688.
Re-applying a manifest with an unchanged UID will now not re-apply the rule unnecessarily. Works properly for negated and non-negated cases.
> Uid negation fix

- lib/puppet/util/firewall.rb
- manifests/linux/redhat.pp
- manifests/params.pp
By adding support for RH7, Amazon was getting incorrectly grouped with those newer operating systems. Amazon Linux is still using the RH6 way to do things making the module unusable on all Amazon systems. I'm adding exceptions for Amazon as the conditions for RH7 were incorrectly catching Amazon Linux because the operatingsystemrelease YYYY.MM will always evaluate to `true`
> Fixing regressions for Amazon Linux since RH7 support was added

- spec/unit/puppet/type/firewallchain_spec.rb
Fixed unit tests to stub out ip6tables version. This seemed to only cause issues on OS X
> Fixed unit tests to stub out ip6tables version.

- lib/puppet/provider/firewall/iptables.rb
- spec/acceptance/firewall_spec.rb
Make sure there's a space after '-A' before gsubbing with '-D'. Was
causing issues with `ensure => absent` and `log_prefix =>
'FW-A-<whatever>'`
> MODULES-1453 - overly aggressive gsub

- lib/puppet/provider/firewall/ip6tables.rb
- manifests/params.pp
- spec/unit/puppet/provider/ip6tables_spec.rb
If the packages for ip6tables aren't installed, the provider will throw an exception. Fix the provider to check to make sure the variable exists first, and update params.pp to include the required package for EL6.
> Modules 633

- README.markdown
Feature lists for `firewall` providers were out of date, and
`physdev_in` and `physdev_out` were listed as features instead of
parameters.
> README updates

- README.markdown
- lib/puppet/provider/firewall/ip6tables.rb
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_spec.rb
This is a.o. needed to fill checksums in UDP packets for
DHCP in VMs using virtual network mode.
> MODULES-1636: Add --checksum-fill support.

- README.markdown
- lib/puppet/type/firewall.rb
- spec/unit/puppet/type/firewall_spec.rb
On CentOS, ipencap is 'ipv4' according to /etc/protocols.
This branch allows matching of protocols for ipv4 and v6 encapsulation.
> Added ipv{4,6} to protocol list

- manifests/linux/redhat.pp
This commit patches the `manifests/linux/redhat.pp` manifest to
perform a `systemctl daemon-reload` exec on platforms that also
contain firewalld.
Prior to this commit, Specifically on Centos 7, if the systemd
deamon is not reloaded then the iptables service fails to start
because it cannot see the systemd Unit for that service.
This patch refreshes the daemon's list of Units and allows the
service to start as expected.
> (MODULES-1984) Perform daemon-reload on systemd

- README.markdown
- lib/puppet/provider/firewall/ip6tables.rb
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_time_spec.rb
Added support for time ipt_module
> Added support for time ipt_module

- manifests/linux/gentoo.pp
- manifests/params.pp
- spec/unit/classes/firewall_linux_archlinux_spec.rb
Previously, Arch Linux was incorrectly assumed to be part of the `RedHat` osfamily. It actually has its own osfamily: `Archlinux`. However, this was added in Facter 1.7.0, and previous versions use an osfamily of `Linux`, so we just check the value of operatingsystem.
Based on #504.
> Fix Arch Linux support

- manifests/linux/debian.pp
On jessie iptables-persistent installation/configuration pops up debconf to ask if the current firewall setup should be saved which leads to puppet hanging and 99% of the time half configured firewall and ssh lockout.
This patch sets the value to false before the install so that debconf doesn't pop up.
> (MODULES-2118) Fix severe installation hang on jessie.

- lib/puppet/provider/firewall/iptables.rb
- spec/fixtures/iptables/conversion_hash.rb
Interpret escape sequences in all string arguments for iptables options.
> (MODULES-1967) Parse escape sequences from iptables

- README.markdown
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/fixtures/iptables/conversion_hash.rb
Note: This test will only fail for ruby 1.9 and above.  I was unable to find a way to reproduce the character encoding functionality introduced in 1.9 on previous versions of ruby in order to construct a test that is useful in those environments.
> (MODULES-1976) Revise rule name validation for ruby 1.9

- spec/spec_helper_acceptance.rb
Reverts puppetlabs/puppetlabs-firewall#548 as per @ruckc and @kresss
> Revert "Don't enable selinux on redhat systems"

- lib/puppet/provider/firewall/iptables.rb
- spec/acceptance/firewall_spec.rb
Improve the regex for `delete_args` to ensure it only matches the `-A` at the beginning of the string to prevent matching `-A ` in the comment field (or anywhere else).
> MODULES-2186 - iptables rules with -A in comment

- README.markdown
- lib/puppet/provider/firewall/ip6tables.rb
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_dscp_spec.rb
- spec/fixtures/iptables/conversion_hash.rb
- spec/unit/puppet/provider/iptables_spec.rb
This adds the ability to make use of --set-dscp and --set-dscp-class flags supported by iptables.  (allowing the setting of DSCP and DSCP Class markings.)
> add set_dscp and set_dscp_class

- README.markdown
Using 'port' allows you to spoof a source port and offers a backdoor by sending a different destination port. sport 80 -> dport 11211 would be valid for 'port => 80' and give access to a memcache instance (port 11211) running on the server.
> Always use dport

- README.markdown
- lib/puppet/type/firewall.rb
- spec/fixtures/iptables/conversion_hash.rb
- spec/unit/puppet/type/firewall_spec.rb
I couldn't find any valid use case for port, and if any valid case did
exist then sport+dport could be used.
> Deprecate port parameter

- lib/puppet/type/firewall.rb
- spec/unit/puppet/type/firewall_spec.rb
When using "port" it currently only throws this warning:
Warning: port is deprecated and will be removed. Use dport and/or sport instead.
In order to avoid having to grep all your installed module code to figure out which module actually throws this warning: add the module name in the warning.
> MODULES-2487 Improve port deprecation warning

- manifests/linux/redhat.pp
Current code throws warning on < 7.x operatingsystemrelease
```
Puppet (warning): Failed to set SELinux context unconfined_u:object_r:iptables_conf_t on /etc/sysconfig/iptables
```
> Include osrelease check in selinux case statement

- lib/puppet/provider/firewallchain/iptables_chain.rb
- lib/puppet/type/firewallchain.rb
- spec/unit/puppet/provider/iptables_chain_spec.rb
- spec/unit/puppet/type/firewallchain_spec.rb
This fixes the following error when the built in "security" table is present.
Error: /Stage[main]/Profiles::Firewall::Stateless/Resources[firewallchain]: Failed to generate additional resources using 'generate': Parameter name failed on Firewallchain[INPUT:security:IPv4]: Inbuilt chains must be in the form {chain}:{table}:{protocol} where {table} is one of FILTER, NAT, MANGLE, RAW, RAWPOST, BROUTE or empty (alias for filter), chain can be anything without colons or one of PREROUTING, POSTROUTING, BROUTING, INPUT, FORWARD, OUTPUT for the inbuilt chains, and {protocol} being IPv4, IPv6, ethernet (ethernet bridging) got 'INPUT:security:IPv4' table:'' chain:'' protocol:''
The target system for this fix is CentOS 7, but it should be applicable to any system with a recent kernel/iptables. …
> MODULES-2769 - Add security table for iptables.

- lib/puppet/provider/firewall/iptables.rb
Some types, specifically the resources type, will call Firewall instances and then use generate to build and add to the catalog firewall resources very early in a Puppet run. Later, those resources might be removed as a side effect of another action, such as shutting down the firewalld service.
Prior to this commit, Puppet would try to delete firewall resources which were already absent, and throw an error. This commit adds an exception catcher which will check to see if the rule being removed is absent, and if so, consider the change a success even if the firewall command failed. It will adjust the change message to reflect the uncertainty over how the rule was removed, though it was verified removed.
> (MODULES-1341) Recover when deleting absent rules

- lib/puppet/type/firewallchain.rb
- spec/unit/puppet/type/firewallchain_spec.rb
This was added to Linux in http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=58a317f1061c894d2344c0b6a18ab4a64b69b815
> Support IPv6 NAT on Linux 3.7+

- manifests/init.pp
- manifests/linux.pp
- manifests/linux/archlinux.pp
- manifests/linux/debian.pp
- manifests/linux/gentoo.pp
- manifests/linux/redhat.pp
- manifests/params.pp
Add a new parameter in order to allow the iptables package to be updated
> allow iptables package to be updated

- lib/puppet/util/firewall.rb
We need to call Facter.flush to clear Facter cache to get up to date value for :iptables_persistent_version.
> (MODULES 3932) - We need to call Facter.flush to clear Facter cache

- lib/puppet/provider/firewall/iptables.rb
Workaround for https://tickets.puppetlabs.com/browse/MODULES-2159 (as described by Greg Murphy in that ticket)
On some distributions (notably on Ubuntu 14.04 and above, and Centos7 and above) the --connlimit-saddr switch is added after the rule is applied causing rule_to_hash to ignore the rule.  Puppet then attempts (and failes) to re-create the rule every time it runs.
> (MODULES-2159) ignore the --connlimit-saddr switch when parsing rules

- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/fixtures/iptables/conversion_hash.rb
- spec/unit/puppet/provider/iptables_spec.rb
Currently puppet throws an error when a (unmanaged) iptables rules contains the `--goto` parameter:
-A w--instance-cfmhvrgpmq6 -g w--default
Error: Could not prefetch firewall provider 'iptables': Invalid address from IPAddr.new: -g
Error: /Firewall[000 accept all icmp]: Could not evaluate: Invalid address from IPAddr.new: -g
This change makes sure puppet doesn't fail.
> (MODULES-3079) Add support for goto argument.

- README.markdown
- lib/puppet/type/firewall.rb
- spec/unit/puppet/type/firewall_spec.rb
While migrating our iptables setup to puppet, we found we could not do it because the `ip` and `pim` protocols weren't supported by the firewall module.
I'm not sure why the module limits the available protos to a subset of those supported by iptables, as the iptables man page says it can support any name used in `/etc/protocols`, and any integer identifier.
Anyhow, this is our quick fix, which works for us.
> Add 'ip' and 'pim' to proto

- lib/puppet/provider/firewall/iptables.rb
- spec/acceptance/resource_cmd_spec.rb
I have the similar issue to #462  and I also fixed that in similar way.
I need to match the rules with -m ttl otherwise puppet will fail with following error:
`Could not prefetch firewall provider 'iptables': Invalid address from IPAddr.new`
> match rules with -m ttl

- lib/puppet/util/firewall.rb
- manifests/linux.pp
This weekend when we updated the vz packages on our servers, they changed our /etc/redhat-release and some other files to say "VirtuozzoLinux" instead of "CloudLinux", so I'm going through finding places where CloudLinux was hardcoded and fixing all (or at least some of) the things.  Thanks for your consideration!
> Add VirtuozzoLinux to the RedHat family

- Gemfile
This is only a temporary measure, as once module-sync runs, this file will be overwritten. This is to make the rspec tests go green until we add support for rspec_puppet 2.4.0
Actual update work to be done in https://tickets.puppetlabs.com/browse/FM-5035
> Pinned rspec_puppet to 2.3.2

- spec/acceptance/nodesets/new/aio/debian-8-64mda.yml
- spec/acceptance/nodesets/new/aio/redhat-6-64mda.yml
- spec/acceptance/nodesets/new/aio/redhat-7-64mda.yml
- spec/acceptance/nodesets/new/aio/ubuntu-1404-64mda.yml
- spec/acceptance/nodesets/new/pe/centos-5-64mda.yml
- spec/acceptance/nodesets/new/pe/centos-6-64mda.yml
- spec/acceptance/nodesets/new/pe/centos-7-64mda.yml
- spec/acceptance/nodesets/new/pe/debian-6-64mda.yml
- spec/acceptance/nodesets/new/pe/debian-7-64mda.yml
- spec/acceptance/nodesets/new/pe/debian-8-64mda.yml
- spec/acceptance/nodesets/new/pe/oracle-6-64mda.yml
- spec/acceptance/nodesets/new/pe/oracle-7-64mda.yml
- spec/acceptance/nodesets/new/pe/redhat-5-64mda.yml
- spec/acceptance/nodesets/new/pe/redhat-6-64mda.yml
- spec/acceptance/nodesets/new/pe/redhat-7-64mda.yml
- spec/acceptance/nodesets/new/pe/scientific-5-64mda.yml
- spec/acceptance/nodesets/new/pe/scientific-6-64mda.yml
- spec/acceptance/nodesets/new/pe/scientific-7-64mda.yml
- spec/acceptance/nodesets/new/pe/sles-10-64mda.yml
- spec/acceptance/nodesets/new/pe/sles-11-64mda.yml
- spec/acceptance/nodesets/new/pe/sles-12-64mda.yml
- spec/acceptance/nodesets/new/pe/ubuntu-1004-64mda.yml
- spec/acceptance/nodesets/new/pe/ubuntu-1204-64mda.yml
- spec/acceptance/nodesets/new/pe/ubuntu-1404-64mda.yml
These nodesets are required for internal CI; to set the ssh timeout.
> (maint) re-add the local nodesets

- spec/spec_helper_acceptance.rb
The man page says it's not implemented for ip6tables.
This was broken by #622 because previously there was an `ip6tables -t nat --flush` that would run and always fail, but the `shell()` call didn't fail because only the LAST return code would be returned (that of `ip6tables -t mangle --flush`).
> (maint) Remove nat flush

- README.markdown
- lib/puppet/provider/firewall/ip6tables.rb
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/fixtures/iptables/conversion_hash.rb
We are using puppetlabs/puppetlabs-firewall in our puppet deployment, however we needed the module to handle the length and string iptables extensions. This pull request contains changes we had to apply.
> (Modules 3329) Add support for iptables length and string extensions

- README.markdown
Added a known issue where MCollective reverses the order of firewall rules with the module and PE.
Also added spaces to the headers in compliance with docs formatting guidance.
> DOC-2683: adding known issue

- README.markdown
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_spec.rb
Support for multiple ipsets in a single rule. This feature is very handy
if you need to match source and destination from different ipsets.
Iptables arguments are a bit wierd, but it works, details are in
https://utcc.utoronto.ca/~cks/space/blog/linux/IptablesIpsetsMultipleMatches
> support for multiple ipsets in a rule

- spec/acceptance/nodesets/new/pe/oracle-5-64mda.yml
Prior to this commit the firewall module did not have a node file
for oracle5 so it was failing in CI. In order to fix this, add the
appropriate config file so tests can be run on oracle5.
> (maint) Add node yaml file for oracle5

- lib/puppet/type/firewall.rb
- manifests/linux/redhat.pp
RHEL7's /usr/libexec/iptables/iptables.init creates the /etc/sysconfig/iptables
file with the wrong selinux parameters, causing spurious changes on the next
run:
[root@ns57zjx0zb7s0b5 ~]# rm -f /etc/sysconfig/iptables
[root@ns57zjx0zb7s0b5 ~]# ls -la /etc/sysconfig/iptables
ls: cannot access /etc/sysconfig/iptables: No such file or directory
[root@ns57zjx0zb7s0b5 ~]# iptables -A INPUT --source 8.8.8.8 -j REJECT
[root@ns57zjx0zb7s0b5 ~]# /usr/libexec/iptables/iptables.init save
iptables: Saving firewall rules to /etc/sysconfig/iptables:[  OK  ]
[root@ns57zjx0zb7s0b5 ~]# ls -la /etc/sysconfig/iptables
-rw-------. 1 root root 259 Nov 19 06:02 /etc/sysconfig/iptables
[root@ns57zjx0zb7s0b5 ~]# /opt/puppetlabs/bin/puppet apply --verbose selinux.pp
Notice: Compiled catalog for …
> (MODULES-4093) Tighten SELinux permissions on persistent files

- lib/facter/iptables_version.rb
When running 'facter iptables_version' it doesn't return a value. The bug seems to in the confine not matching the right kernel value.
> iptables_version fact doesn't return the version

- manifests/linux/redhat.pp
- spec/unit/classes/firewall_linux_redhat_spec.rb
- spec/unit/classes/firewall_linux_spec.rb
Since the autobefore fix on the firewall type is not available for puppet 3,
this re-adds the RHEL7 workaround if we're running on puppet 3.
Closes #659
> Re-add RHEL7 SELinux support for puppet3

- manifests/linux/redhat.pp
Centos 7 has different user/type for SELinux than other EL7 platforms.
> (MODULES-4173) Fixes selinux issues on centos7

- lib/puppet/provider/firewall/iptables.rb
This change adds the --wait flag to the insert/update/delete iptables
actions to prevent failures from occuring when iptables is running
outside of puppet. Previously if a script or a user is running iptables
commands while puppet is running, there may be failures in the firewall
provider if iptables cannot get a lock. By default, iptables will just
fail with an error so using --wait will make it wait until a lock can be
established.
> Add --wait to iptables commands

- README.markdown
- manifests/init.pp
- manifests/linux.pp
- manifests/linux/redhat.pp
- manifests/params.pp
- spec/unit/classes/firewall_linux_redhat_spec.rb
For the redhat OS family the service for managing ip6tables is called
ip6tables. This service is currently not managed with this module.
This commit fixes this issue by introducing an additional parameter
$service_name_v6 for the ipv6 version of the service.
> (MODULES-3572) Ip6tables service is not managed in the redhat family.

- lib/facter/ip6tables_version.rb
When running the 'facter ip6tables_version' it returns a empty string. The problem is in the confine :kernel => linux line. Adjusted this to capital L.
> ip6tables_version fact doesn't return the version

- lib/puppet/provider/firewall/iptables.rb
If there are double quotes in the comment, the adding of the rule would work fine, but when it came to remove the rule, the double quotes were removed, and the rule was never removed from the system.
This fix will make sure that it only removes the quotes from the beginning and end of the string.
> Fixing issue with double quotes being removed when part of the comment

- manifests/linux/redhat.pp
This originally started as a fix for a puppet lint issue in CI, where the $seluser variable had been removed from the firewall::linux::redhat class as seluser property for the File["/etc/sysconfig/${service_name}"] resource is now set in a case statement. 
When a separate PR was merged adding the 'service_name_v6' param, it still used the $seluser variable to set the seluser property of the File["/etc/sysconfig/${service_name_v6}"] resource.
When both these PR's were merged they then caused a puppet lint error in CI.
> Add RHEL7 SELinux support for new service_name_v6 param, subsequently fix puppet lint error

- lib/puppet/provider/firewall/ip6tables.rb
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
This add the geoip module to the firewall.
I am not very good with ruby, so if somebody can help me out with the spec tests it would be nice.
Except from that, everything works fine
> MODULES-4279 Add support for the geoip module

- spec/acceptance/firewall_bridging_spec.rb
Move physdev_is_in and physdev_is_out tests to block with the rest of the 'ip6tables physdev tests' which do not run on EL5 or SLES 10 due to iptables version 1.3.5 is not suppored by the ip6tables provider on those platforms.
This is a result of PR #685 causing CI failures on Redhat 5 and Scientific 5.
> [MODULES-4234] Move physdev_is_in and physdev_is_out tests

- manifests/linux/redhat.pp
The SELinux context for the iptables configuration file was not being set
properly on Redhat based platforms.  The default context for this file
is 'system_u:object_r:system_conf_t:s0' which is shown by using the restorecon command.
> Change - Ensure that the iptables configuration file has proper context

- lib/puppet/provider/firewall/ip6tables.rb
- lib/puppet/provider/firewall/iptables.rb
The geo rules will be generated over and over again if the matching options are not exactly the same.
So it has to be --source-country instead of --src-cc.
Without that, every puppet run will generate the geo rules new and dont purge the old ones.
> MODULES-4279 use complete option for geoip

- manifests/linux/redhat.pp
- spec/unit/classes/firewall_linux_redhat_spec.rb
firewalld must be stopped and disabled before the iptables service
will start properly.
> Change - Ensure that firewalld is stopped before iptables starts

- README.markdown
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/acceptance/nflog_spec.rb
- spec/unit/puppet/type/firewall_spec.rb
This adds four new features to the firewall type: nflog_groups, _range, _prefix, and _threshold. Unit tests and acceptance tests were also added.
> (FM-4896) add NFLOG support

- spec/acceptance/nflog_spec.rb
for nflog_spec we check iptables-save output and for --nflog-prefix, there can be varying amounts of space, so this accounts for that
> (maint) modify to account for spaces in iptables-save output

- lib/puppet/provider/firewall/iptables.rb
- spec/acceptance/nflog_spec.rb
NFLOG is not available as a jump target until iptables version 1.3.7.
This adds an error to the provider when the version is lower than 1.3.7
and the user tries to use NFLOG options. This also updates the tests to
check and make sure the error is thrown on appropriate versions
> (maint) do not test nflog on older versions of iptables ( < 1.3.7)

- metadata.json
Update the puppetlabs-firewall module version compatibility in the metadata.json to: "version_requirement": ">= 4.7.0 < 5.0.0"
The current version_requirement is listed as ">= 3.5.0 < 5.0.0"
> MODULES-4828 version_requirement updated

- README.markdown
- spec/unit/documentation/readme_spec.rb
commit 95f56586a6506ce4c0460106483a7982fbaf4e05
Author: Alex Harvey <Alex_Harvey@amp.com.au>
Date:   Sun Jun 11 22:47:18 2017 +1000
Add test for README
This adds an Rspec test to fail the build if someone adds incorrectly
formatted heading markers again.
commit b7b62ec28f9999ca499440838d26733aab530eb8
Author: Alex Harvey <Alex_Harvey@amp.com.au>
Date:   Sun Jun 11 22:31:33 2017 +1000
(doc) Fix formatting in README.markdown
Without this patch applied, a large chunk of the README is not
displaying properly on Github.
> (doc) Fix formatting in README.markdown

- README.markdown
- lib/puppet/type/firewall.rb
- spec/unit/puppet/type/firewall_spec.rb
Type updated to permit UNTRACKED to be passed as a valid state
README updated to document above change
Spec tests updated to verify UNTRACKED is accepted for both state and ctstate, and additionally to verify alphabetic ordering still works as expected.
All tests relating to these changes have passed.
> (MODULES-5111) Support UNTRACKED in state and ctstate rules

- lib/puppet/provider/firewall/iptables.rb
- spec/fixtures/iptables/conversion_hash.rb
This patch allows the provider to understand rules that contain negated
match sets when parsing the ruleset.
> (MODULES-5340) Understand negated match sets

- spec/acceptance/hashlimit_spec.rb
Hashlimit doesn't seem to be fully supported on these OS'es so I've put a check to skip the tests.
> Update for hashlimit tests to not run on RedHat5 or Scientific 5

- .fixtures.yml
- manifests/init.pp
- manifests/linux.pp
- manifests/linux/redhat.pp
- metadata.json
- spec/spec_helper_acceptance.rb
- spec/unit/classes/firewall_linux_redhat_spec.rb
many hardened systems have IPv6 disabled, which
does not allow ip6tables to be running.  allow
ip6tables to be selectively disabled in these cases.
errors when IPv6 is disabled:
Error: Could not start Service[ip6tables]: Execution of '/usr/bin/systemctl start ip6tables' returned 1: Job for ip6tables.service failed because the control process exited with error code. See "systemctl status ip6tables.service" and "journalctl -xe" for details.
Error: /Stage[main]/Firewall::Linux::Redhat/Service[ip6tables]/ensure: change from stopped to running failed: Could not start Service[ip6tables]: Execution of '/usr/bin/systemctl start ip6tables' returned 1: Job for ip6tables.service failed because the control process exited with error code. See "systemctl status ip6tables.service" and "journalctl -xe" …
> allow ip6tables to be disabled

- lib/puppet/type/firewall.rb
- lib/puppet/util/firewall.rb
- lib/puppet/util/ipcidr.rb
- spec/unit/puppet/util/firewall_spec.rb
Currently hostnames specified in a `source` or `destination` field
in a firewall rule are always resolved as IPv4, even when the
provider is `ip6tables`. Instead, intelligently determine whether
the hostname should be resolved as an IPv4 address or IPv6 address
based on the provider.
> (MODULES-5645) Choose correct IP version for hostname resolution

- README.markdown
> (docs) Add missing hyperlink

- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_gid_spec.rb
The "uid" parameter for the firewall type correctly deals with mapping between usernames and UIDs as required, however the same isn't true for GIDs, which leads to spurious changes on every puppet run. This PR adds a similar mapping to GIDs.
> Add gid lookup

- lib/puppet/provider/firewall/iptables.rb
- spec/fixtures/iptables/conversion_hash.rb
- spec/unit/puppet/provider/iptables_spec.rb
We have manual and puppet controlled chains, and someone manually added rule like this:
`-A INPUT -s 1.2.3.4/32 -p tcp -m -tcp --dport 80 --tcp-flags FIN,SYN,RST,ACK SYN -m comment --comment "some comment" -j ACCEPT`
and puppet started throwing errors like:
`Could not evaluate: Invalid address from IPAddr.new: 80`
After some digging I've found that the rule is not properly parsed because of the `--dport 80` between `-m tcp` and `--tcp-flags`. Similar issues can be expected with other combined arguments from the resource_map. It's hard to cover all those cases so I've added simple sanity check for the parser.
https://tickets.puppetlabs.com/browse/MODULES-4200
> (MODULES-4200) Add simple sanity check for the rule to hash parser

- lib/puppet/provider/firewall/iptables.rb
We have two kind of unmanaged rules:
- empty comment: those get an md5 hash as a name prefixed with 90XX
- comment not matching “\d[graph,space]+$”
This is defined there[1]
But when we calculate the updated line we take into account only the
first kind of unmanaged rule in the offset[2] which leads to error.
Relaxing the regex solves this.
[1] https://github.com/puppetlabs/puppetlabs-firewall/blob/master/lib/puppet/provider/firewall/iptables.rb#L610..L617
[2] https://github.com/puppetlabs/puppetlabs-firewall/blob/master/lib/puppet/provider/firewall/iptables.rb#L802..L803
> [MODULES-5924] Fix unmanaged rule regex when updating a iptable.

- lib/puppet/provider/firewall/iptables.rb
- spec/fixtures/iptables/conversion_hash.rb
- spec/unit/puppet/provider/iptables_spec.rb
The iptables rules parser has very strict/simplistic expectations
about how iptables rules should look like, and can easily fail to
parse rules that weren't produced by the module itself.
We should ignore the unfitting rules when parsing and produce a
warning rather than causing a fatal error and stopping the Puppet run.
> (MODULES-6029) Skip unparsable rules with warning

- spec/unit/puppet/provider/iptables_spec.rb
I used the puts to figure out rspec behavior and forgot to remove it
before commiting a fix.
> Remove leftover debugging 'puts'

- lib/puppet/provider/firewall/iptables.rb
- spec/fixtures/iptables/conversion_hash.rb
Add a a zero width lookbehind to the regex that processes negations to avoid matching the dash in the chain name.
> MODULES-6261: Fix error parsing rules with dashes in the chain name

- manifests/linux/redhat.pp
In 1.10.0, applying the puppetlabs-firewall module on CentOS/RHEL 5.x produces warnings:
Warning: Failed to set SELinux context unconfined_u:object_r:etc_t on /etc/sysconfig/iptables
Notice: /Stage[main]/Firewall::Linux::Redhat/File[/etc/sysconfig/iptables]/seluser: seluser changed 'system_u' to 'unconfined_u'
Warning: Failed to set SELinux context unconfined_u:object_r:etc_t on /etc/sysconfig/ip6tables
Notice: /Stage[main]/Firewall::Linux::Redhat/File[/etc/sysconfig/ip6tables]/seluser: seluser changed 'system_u' to 'unconfined_u'
This commit adds a case to set the correct seluser.
> (MODULES-6092) Set correct seluser for CentOS/RHEL 5.x

- manifests/linux/debian.pp
- manifests/params.pp
- spec/fixtures/ip6tables/conversion_hash.rb
- spec/fixtures/iptables/conversion_hash.rb
Using PDK to convert module so that it is compliant with the PDK.
The second commit addresses a bundler issue MODULES-6339.
The next time PDK convert is ran it will re-add the newer version of the bundler gem.
> (maint) - Address rubocop & puppet lint errors

- lib/puppet/provider/firewall/iptables.rb
This fixes the issues with rules in the following format (e. g. used by Docker),
where exclamation mark precedes an option followed by outiface:
```
"-A FORWARD -i br-123456 ! -o br-123456 -j ACCEPT"
```
Without the fix, it is being parsed like [this:](https://github.com/puppetlabs/puppetlabs-firewall/blob/master/lib/puppet/provider/firewall/iptables.rb#L396)
```
values = values.gsub(/(-\S+) (!)\s?(\S*)/,'\1 "\2 \3"')
#=> "-A FORWARD -i br-123456 \"! -o\" br-123456 -j ACCEPT"
values = values.gsub(/(!)\s*(-\S+)\s*(\S*)/, '\2 "\1 \3"')
#=> "-A FORWARD br-123456 \"-o\" \"! br-123456\" ACCEPT"
```
Which, in the end, results in:
```
values = ["ACCEPT", "\"! br-123456\"", "\"-o\"", "br-123456", "FORWARD"]
keys = [:jump, :iniface, :chain]
Error: Failed to apply catalog: Parser error: keys (3) …
```
> (MODULES-6129) negated option with address mask bugfix

- lib/puppet/provider/firewall/iptables.rb
- spec/unit/puppet/provider/iptables_spec.rb
This change works around a bug in ip6tables where rules will not be deleted if they attempt to match the 'all' protocol, as it does not properly handle a missing protocol field as an implicit 'all':
netfilter bug located here: https://bugzilla.netfilter.org/show_bug.cgi?id=1015
> (MODULES-2119) iptables delete -p all exception

- manifests/linux/redhat.pp
setting service provider explicit to systemd as pupppets default does
not work for Amazon Linux 2
> Add support for Amazon Linux 2

- metadata.json
Gentoo is an entry in the metadata, removing this entry as we do not
have our test infrastructure set up to run acceptance test on this
OS. Removing from the metadata means that we will not support this OS,
however no code changes are being made therefore this OS may still be
compatible.
> (FM-7516) - Removing Gentoo from metadata

- lib/puppet/provider/firewall/ip6tables.rb
In lib/puppet/provider/firewall/ip6tables.rb there is no goto: entry for the -g flag in @resource_map which leads to errors for rules using that feature. 
lib/puppet/type/firewall.rb already handles this flag. It's a one-line change to recognize it. The right rules then get into the chains in my testing.
> add -g flag handling in ip6tables.rb provider

- README.markdown
- lib/puppet/type/firewall.rb
Updated regex match for iniface and outiface in lb/puppet/type/firewall.rb
Updated reference in README.markdown to reflect changes in regex.
> Changed regex for iniface and outiface to allow '@' in interface names

- lib/puppet/provider/firewall/iptables.rb
- spec/acceptance/resource_cmd_spec.rb
- spec/fixtures/iptables/conversion_hash.rb
As iptables/iptables-save accepts multiple '-m comment --comment' parameters,
we should find and merge them all together to avoid generating warnings.
Since puppet resource allows you to create only single comment, this should only
affect rules, which are not managed by puppet.
> (MODULES-7990) Merge multiple comments into one while parsing rules

- manifests/linux/redhat.pp
- manifests/params.pp
- spec/unit/classes/firewall_linux_redhat_spec.rb
In RHEL8, iptables is replaced with nftables under the covers. In order
to allow for the firewall module to continue to function, this change
updates the redhat firewall configuration to pull in the nftables
packages.
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/8.0_beta_release_notes/new-features#networking_2
> Add nftables wrapper support for RHEL8

- README.markdown
- lib/puppet/provider/firewall/iptables.rb
- spec/acceptance/firewall_spec.rb
When a user specifies a firewall rule starting with a value between 9000-9999, the following error is thrown:
```Error: Could not set 'present' on ensure: undefined method `+' for nil:NilClass at /root/manifest.pp:2```
The following change addresses this by raising a more appropriate error and providing information in the README as to why this error occurs.
> (MODULES-6340) - Address failure when name begins with 9XXX

- lib/puppet/provider/firewall/iptables.rb
- spec/unit/puppet/provider/iptables_spec.rb
A fix for Bugzilla #1015 was added in
680738164865a01f554d1e1037c8d8724e39a720. However, it appears that the
bug description at https://bugzilla.netfilter.org/show_bug.cgi?id=1015
is not quite accurate, and the -p all hack is required sometimes, but
not always. I don't know exactly when it is or isn't required.
This patch changes the logic to try both.
> (MODULES-8360) Fix IPv6 bug relating to Bugzilla 1015

- README.markdown
Remove the reference that suggests the ordering number used for rules isn't restricted to the section the rule is in. This is misleading and can lead to mis-configured firewall rules.
For more information, see https://tickets.puppetlabs.com/browse/DOC-3056.
> (DOC-3056) Remove mention of rules ordering

- README.markdown
- manifests/linux/redhat.pp
- spec/acceptance/invert_spec.rb
- spec/acceptance/rules_spec.rb
SLES 11 Sp4 seems to default to ‘-m conntrack’ rather than ‘-m state’
In addition, adding back a piece of code for Centos 5
> (MODULES-8648) - Fix for failures on SLES 11

- manifests/linux/debian.pp
Often, the iptables-persistent package in debian-based distributions is controlled by external modules. Can I replace the package installation with `package{}` on `ensure_pacakges()`?
> External control for iptables-persistent

- spec/acceptance/firewall_attributes_exceptions_spec.rb
- spec/acceptance/firewall_attributes_happy_path_spec.rb
ipvs not on RedHat 5/6 by default so moving this to exception spec to fix failing tests.
> (MODULES-8855) Move ipvs test to exception spec

- manifests/linux/redhat.pp
- manifests/params.pp
- spec/unit/classes/firewall_linux_redhat_spec.rb
In order to persist the nftables rules on RHEL8, we need the init scripts:
"Warning: Firewall[998 log all ipv4](provider=iptables): Unable to persist firewall rules:
Execution of '/usr/libexec/iptables/iptables.init save' returned 1:
Error: Could not execute posix command: No such file or directory - /usr/libexec/iptables/iptables.init",
Those are contained in the iptables-services package, so this patch aims
to add it into package_name for RHEL8.
Also, to make the IPtables-managed rules persistent at reboot, we need
to enable iptables (and ip6tables) service(s) like we did in previous
versions of RHEL ecosystem.
> (MODULES-8736) IPtables support on RHEL8

- metadata.json
- spec/acceptance/firewall_attributes_exceptions_spec.rb
- spec/acceptance/firewall_attributes_ipv6_exceptions_spec.rb
- spec/acceptance/firewall_attributes_ipv6_happy_path_spec.rb
RedHat 8 iptables uses an nftables backend. The `time` match extension
does not appear to be supported. As such, I have moved the test into
exceptions spec.
https://wiki.nftables.org/wiki-nftables/index.php/Supported_features_compared_to_xtables#time
> (FM-8025) Add RedHat 8 support

- lib/puppet/type/firewall.rb
- lib/puppet/type/firewallchain.rb
I've just fixed a couple of typos I noticed while using the module, the word 'yphen' where it should be 'hyphen' and the case of the argument error when creating a chain.
> Typo fixes

- REFERENCE.md
- lib/puppet/type/firewall.rb
The `reject` attribute noted `jump => 'REJECT'`. But, the `jump` attribute notes that "for the values ACCEPT, DROP, and REJECT, you must use the generic `action` parameter." (Also, added some commas...)
> Make the reject attribute note consistent

- lib/puppet/provider/firewall/iptables.rb
- spec/fixtures/iptables/conversion_hash.rb
Fix parsing rules which have comments including a hyphen mark and no space character.
Example: 101-a-b-c.
> Fix parsing iptables rules with hyphen in comments

- manifests/init.pp
This module will cause puppet agent runs to fail when it is included
on a windows node.  Updated manifest to do nothing when running on
a windows client.
> Change - Avoid puppet failures on windows nodes

- lib/facter/iptables_persistent_version.rb
- manifests/params.pp
- spec/unit/classes/firewall_linux_debian_spec.rb
Replacement PR for https://github.com/puppetlabs/puppetlabs-firewall/pull/805
- Added operatingsystemrelease unstable with netfilter service and package
- Extended rspec tests for Debian
> Add support for Debian Unstable

- lib/puppet/provider/firewall/ip6tables.rb
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/unit/puppet/type/firewall_spec.rb
I would like to add more support for conntrack module options (http://ipset.netfilter.org/iptables-extensions.man.html). These changes do include modifying the existing ctstate option to use the module argument mapping so that the additional options can be added.
> Support conntrack module

- lib/puppet/provider/firewall/ip6tables.rb
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_attributes_exceptions_spec.rb
- spec/acceptance/firewall_attributes_happy_path_spec.rb
This is the rule from Kubernetes that was breaking the iptables-save parsing:
```
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE --random-fully
```
This was the full error:
```
Debug: Puppet::Type::Firewall::ProviderIptables: [instances]
Debug: Executing: '/usr/sbin/iptables-save'
Error: /Firewallchain[OUTPUT:filter:IPv4]: Failed to generate additional resources using 'generate': Parser error: random was meant to be a boolean but received value: true-fully.
/opt/puppetlabs/puppet/cache/lib/puppet/provider/firewall/iptables.rb:589:in `block in rule_to_hash'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/firewall/iptables.rb:587:in `each'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/firewall/iptables.rb:58 …
```
> Add random_fully and rpfilter support

- lib/puppet/provider/firewall/ip6tables.rb
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_attributes_happy_path_spec.rb
Hello, 
I added  booleans for the LOG options `--log-tcp-sequence --log-tcp-options --log-ip-options`
Let me know if you need any changes to the PR. Happy to help.
Cheers,
Markus
> Extend LOG options

- REFERENCE.md
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/fixtures/iptables/conversion_hash.rb
This adds the cgroup matcher, which allows matching packets based on their net_cls cgroup ID.
> Add support for cgroup arg

- lib/puppet/provider/firewall/iptables.rb
- spec/fixtures/iptables/conversion_hash.rb
This is a clone of [this PR](https://github.com/puppetlabs/puppetlabs-firewall/pull/889) but on an up-to-date master
> Add support for u32 module in iptables

- spec/spec_helper_acceptance_local.rb
Tests failing on RHEL systems as the `install_iptables` method
always assumed it was running against Debian / Ubuntu.
> (IAC-1025) Fix spec test helper method

- lib/puppet/provider/firewall/iptables.rb
- spec/fixtures/iptables/conversion_hash.rb
Hello,
we've been using Puppet quite heavily at Opera. Recently I started rolling out fresh version of firewall module on our hosts and noticed a lot of corrective changes being applied, e.g.:
```
Notice: /Stage[main]/Osp_firewall/Firewall[099_a_long_example_rule_with_underscores]/action: current_value , should be 'accept' (noop) (corrective)
```
I think I traced the problem to regex in iptables provider being too greedy and removing suffix with jump target instead of just the name of the rule. I believe the issue is best visible [via regexr](https://regexr.com/59m2h).
Cheers,
> Fix problem with parsing rules without quotes

- lib/puppet/type/firewall.rb
- spec/fixtures/iptables/conversion_hash.rb
As reported by Steve Traylon[1] and @patricknelson[2], the munging adds extra quotes to the string.
This breaks the string matching in iptables, as it looks for literal single quotes in the match.
Removing the munging fixes this.
[1] https://tickets.puppetlabs.com/browse/MODULES-3454?focusedCommentId=686988&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-686988
[2] https://github.com/puppetlabs/puppetlabs-firewall/commit/3655c6bd33d662a3813c2f66cd0bc5889c68c2c2#diff-379160b60a9bdf297b92a51d20efd8c3R1426
> Fix extra quotes in firewall string matching

- README.md
- lib/puppet/type/firewallchain.rb
This stops `firewallchains` from purging rules that do not look
like rules the module puts into place. This capability can be used
to co-exist with other firewall management solutions on the same
machine.
Improved flow in the README around setting up purging, make it
a user decision to enable, and add a pointer to `ignore_foreign`.
> (IAC-1190) add `ignore_foreign` when purging firewallchains

- NOTICE
The copyright names were incorrectly removed by
00a1f3fb0369f5b4ca474a681114fbfd8c9f81bf as part of a modulesync
> Restore copyright names

- README.md
- lib/puppet/provider/firewall/ip6tables.rb
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_attributes_exceptions_spec.rb
- spec/spec_helper_acceptance_local.rb
- spec/unit/puppet/type/firewall_spec.rb
> (IAC-966) - MODULES-10522: Add support for the --condition parameter

- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_attributes_exceptions_spec.rb
It looks that `mac_source` parameter cannot be applied idempotently on `sles-15` iptables downcase the value.
For example: `'0A:1B:3C:4D:5E:6F' --> '0a:1b:3c:4d:5e:6f'`. And puppet triggers this as `Properties changed - updating ruled`
```shell
Notice: Compiled catalog for litmus-0bf65b80828b158e.c.ia-content.internal in environment production in 0.08 seconds
Notice: /Stage[main]/Main/Firewall[610 - test]/mac_source: mac_source changed '0a:1b:3c:4d:5e:6f' to '0A:1B:3C:4D:5E:6F'
Notice: Firewall[610 - test](provider=iptables): Properties changed - updating rule
Notice: Applied catalog in 0.14 seconds
```
> sles-15: mac_source is downcased by iptables

- lib/puppet/type/firewall.rb
According to the firewall module [HISTORY.md](https://github.com/puppetlabs/puppetlabs-firewall/blob/main/HISTORY.md#2015-07-28---supported-release-170) `Facter.fact().value()` is not supported by `Facter 3` - `Replace Facter.fact().value() calls with Facter.value() to support Facter 3`
I added by mistake trying to repair our nightly CI. This PR should repair users problems created by the previous commit and not block our nightly CI
kind regards,
@adrianiurca
> (MODULES-11138) - Fix mac_source Facter.fact().value() issue with Facter 3

- lib/puppet/type/firewall.rb
Hi,
Currently when updating an existing rule that did not have `uid` specified to include an `uid` the module fails with the following:
```
Error: undefined method `gsub' for nil:NilClass
Info: Unknown failure using insync_values? on type: Firewall[100 OUTPUT IPSEC isakmp access] / property: uid to compare values [nil] and 
Error: /Stage[base]/Node_templates::Softrouter::Ipsec/Firewall[100 OUTPUT IPSEC isakmp access]/uid: change from  to 'root' failed: undefined method `gsub' for nil:NilClass
```
It appears that `uid.insync?` [property](https://github.com/puppetlabs/puppetlabs-firewall/blob/main/lib/puppet/type/firewall.rb#L1376) (along with `gid` [one](https://github.com/puppetlabs/puppetlabs-firewall/blob/main/lib/puppet/type/firewall.rb#L1423)) do not support when `is` is `nil` (see …
> Fix "undefined method `gsub' for nil:NilClass" when changing existing rule UID from absent to any present

- lib/puppet/type/firewall.rb
- spec/unit/puppet/type/firewall_spec.rb
On Gentoo using 'vrrp' sets the proto to 112 but when puppet runs it interprets 112 as 'carp' which it then corrects to 'vrrp' which is still 112. So it redoes the rule every time puppet runs. Adding carp here allows carp to be set as a valid option which removes the loop.
> Add carp protocol to :proto property

- manifests/linux.pp
- manifests/params.pp
Improvement on PR - https://github.com/puppetlabs/puppetlabs-firewall/pull/1016 (https://github.com/puppetlabs/puppetlabs-firewall/pull/1016#discussion_r716869019)
See BUG - https://tickets.puppetlabs.com/browse/MODULES-11147
This minor change to the package to use the name field and param should also mean supporting other distros/package names be much easier, where as prior it was static.
Completely untested on Debian Distros; Tested on CentOS7, Fedora 33, Fedora 34. Can't forsee any issues.
> Fedora 34 and iptables-compat fix; properly utilising iptables param.

- README.md
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_duplicate_comment_spec.rb
- spec/spec_helper_acceptance_local.rb
In certain situations it is possible for an unmanaged rule to exist on the target system that has the same comment as the rule specified in the manifest.
When this condition is true puppet will ignore the the unmanaged rule and continue to apply the rule in the manifest. This is because the firewall module uses the comment field in IPT as it's namevar and therefore expects it to be a unique identifier. In the case of IPT this is not true given that you can have multiple rules with the same comment.
This commit adds a check that will identify system rules that have their comment field set to the same value as a rule in the manifest. If we enter a situation where any of the duplicate counts are greater than 1 then we will respond with a configurable action. The behaviour of this can be …
> (SEC-944) Handle duplicate system rules

- lib/puppet/provider/firewall/ip6tables.rb
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
Hi,
In the current version of the module, the `rpfilter` parameter works as a no-op, no matter which value is provided since the feature is not specified. This commit fixes this issue.
Unfortunately, this is not the only issue with the parameter in question. The [xt_rpfilter](https://ipset.netfilter.org/iptables-extensions.man.html#lbBX) is one of the few extensions that perform meaningful work even when there are no extra parameters specified (in fact the default `strict` mode is invoked by just the `-m rpfilter` stanza), and currently, the Puppet module requires for the mode to be set to one of `loose`/`validmark`/`accept-local`/`invert`. In fact, all of these are optional flags and can be enabled simultaneously or not enabled at all. I'm not sure how to fix this and whether I should …
> Fix rpfilter parameter

- lib/puppet/util/firewall.rb
allow persistence of firewall rules for Suse by using `iptables-save`.
> allow persistence of firewall rules for Suse

- lib/puppet/type/firewall.rb
- metadata.json
(GH-cat-11) Certify Support for Ubuntu 22.04
pdk version: `2.4.0`
> pdksync - (GH-cat-11) Certify Support for Ubuntu 22.04

- lib/puppet/provider/firewall/iptables.rb
Issues have arisen with the --random-fully value on certain RedHat versions.
It seem's as if the logic put in around `--random` and `--random-fully` are no longer working.
This change should resolve the issue and tighten the logic around the `known_boolean` values.
> (GH-1055) Fix for `--random-fully`

- lib/puppet/type/firewall.rb
- spec/unit/puppet/provider/iptables_spec.rb
The existing code passes `:proto`, which `string_to_port` casts to a
string, gets "proto", compares that to the possibilities "udp" or "tcp",
and when neither, falls back to using "tcp".
This patch passes the actual proto value to the function, in case there is
a UDP specific service in your /etc/services (uncommon, but it happens).
It looks like Puppet will evaluate the properties in declared order,
so I had to move `newproperty(:proto)` up so `@resource[:proto]` was
available in the code for `sport`, `dport` and `port`.
> fix service port number lookup to use protocol

- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_attributes_exceptions_spec.rb
Now you can not only
```
match_mark => '0x02'
```
but also
```
match_mark => '! 0x02'
```
> Add negate to match_mark

- lib/puppet/type/firewall.rb
- manifests/linux/debian.pp
- spec/acceptance/firewall_attributes_exceptions_spec.rb
Reverts puppetlabs/puppetlabs-firewall#1066
Prior to this commit nightlies and all tests on main are failing. 
This commit reverts a PR that was merged as it looked sensible and and suggested all tests passed. However as an oversight only the CLA check ran therefore the test results presented were misleading. Initially I tried to resolve with adding the missing `end` however the failures run deeper than this therefore the best decision would be to revert this PR.
> Revert "Add negate to match_mark"

- lib/facter/ip6tables_version.rb
- lib/facter/iptables_persistent_version.rb
- lib/facter/iptables_version.rb
- spec/unit/facter/iptables_persistent_version_spec.rb
- spec/unit/facter/iptables_spec.rb
Prior to this PR, this module contained instances of Facter::Util::Resolution.exec and Facter::Util::Resolution.which, which are deprecated. This PR aims to replace these exec helpers with their supported Facter::Core::Execution counterparts.
This PR:
- Replaced all Facter::Util::Resolution instances with corresponding Facter::Core::Execution exec helpers
> (CONT-173) - Updating deprecated facter instances

- lib/facter/iptables_persistent_version.rb
- lib/puppet/type/firewall.rb
- manifests/linux/debian.pp
- manifests/linux/redhat.pp
- manifests/params.pp
- spec/unit/classes/firewall_linux_debian_spec.rb
- spec/unit/classes/firewall_linux_redhat_spec.rb
- spec/unit/classes/firewall_linux_spec.rb
- spec/unit/puppet/provider/ip6tables_spec.rb
- spec/unit/puppet/provider/iptables_chain_spec.rb
- spec/unit/puppet/provider/iptables_spec.rb
Prior to this commit, the firewall modules had multiple instances of outdated code.
This commit aims to clean-up some of that code to keep the module clean and readable.
> (CONT-256) Removing outdated code

- metadata.json
Prior to this commit, and as part of the codebase hardening project, we sanitised some commands in the module. However, this sanitisation method requires that users have at least puppet version 6.24.0 and onwards to be effective.
This commit aims to resolve that requirement by raising the required puppet version in the metadata.json file.
> (CONT-5) Raising minimum required puppet version

- manifests/linux/redhat.pp
Prior to this commit, and after the work perform in CONT-256, there were a few commands in the module that were not properly sanitised according to our current standards.
This PR aims to implement some changes that ensure no malformed commands are passed through to the system. Primarily, the commands targeted were the ones related to Open3 and exec.
> (CONT-5) Codebase hardening

- metadata.json
Reverts puppetlabs/puppetlabs-firewall#1088
Firewall codebase hardening does not include any 'unless' nor 'onlyif' updates. Therefore, raising the minimum puppet required version may not be necessary.
> Revert "(CONT-5) Raising minimum required puppet version"

- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_attributes_happy_path_spec.rb
When rules with rpfilter are used, then there are warnings like these in the output:
`Warning: Puppet::Type::Firewall::ProviderIptables: Skipping unparsable iptables rule: keys (5) and values (6) count mismatch on line: -A cali-PREROUTING -m comment --comment "cali:mPIOOWmbH3iO0R90" -m mark --mark 0x40000/0x40000 -m rpfilter --validmark --invert -j DROP`
> add support for using rpfilter in rules

- README.md
- lib/puppet/provider/firewall/ip6tables.rb
- lib/puppet/provider/firewall/iptables.rb
- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_attributes_exceptions_spec.rb
--nflog-range was deprecated way back in 2016.
https://git.netfilter.org/iptables/commit/?h=v1.6.1&id=7070b1f3c88a0c3d4e315c00cca61f05b0fbc882
> support --nflog-size as replacement for --nflog-range

- manifests/params.pp
There are some pointers given by dnf about "iptables", but these confuse Puppet into aborting with the error message:
```console
Error: /Stage[main]/Firewall::Linux/Package[iptables]: Could not evaluate: no implicit conversion of Array into Hash
```
Fedora had a similar patch in commit 486e4b5779f5069e which I think fixed the bug https://tickets.puppetlabs.com/browse/MODULES-11147 but the same issue rared its head here on AlmaLinux 9.0.
The RPM for iptables-legacy states:
> This package contains the legacy tools which are obsoleted by
> nft-variants in iptables-nft package for backwards compatibility reasons.
> If you need to set up firewalls and/or IP masquerading, you should not install
> this package but either nftables or iptables-nft instead.
> package "iptables" has been replaced by "iptables-nft" on EL9

- lib/facter/ip6tables_version.rb
- lib/facter/iptables_persistent_version.rb
- lib/facter/iptables_version.rb
- spec/unit/facter/iptables_persistent_version_spec.rb
- spec/unit/facter/iptables_spec.rb
Fix for https://github.com/puppetlabs/puppetlabs-firewall/issues/1093
Prior to this PR, work was carried out on this module to update all instances of the now deprecated Facter::Util::Resolution, and replace all with its newer and supported counterpart Facter::Core::Execution. 
However, these do not behave exactly the same. 
Facter::Util::Resolution initially ran a which to locate the binary before executing, preventing any errors from occuring. The newer Facter::Core::Execution method did not do this, instead it attempted to execute.
This commit aims to introduce an "on_fail:false" flag to each execute statement, so that a failed execute will return false (boolean) and not generate an error.
> (1093) - Fix unresolved fact error

- metadata.json
Prior to this commit, due to a mistake, there was a reversion to the previously implemented bump to minimum required puppet version, which was part of the CVE update.
This commit aims to address issue 1097 in Github which brings to light the need for this puppet bump to be restored to 6.24
> (GH-1097) Bumping back required puppet version

- manifests/init.pp
to prevent bailing out in case it gets pulled in by other modules.
> Ignore OpenBSD, similarly to FreeBSD

- README.md
- lib/puppet/provider/firewallchain/iptables_chain.rb
Flush chain to get rid of unmanaged firewall rules in that chain else the remove of the chain will fail.
---
This PR fixes #1064 where you want to ensure that all unmanaged firewall chains and rules are removed but still want to be able to whitelist unmanaged rules of a chain via `ignore` or `ignore_foreign`.
Code to reproduce:
```puppet
resources { 'firewallchain':
purge => true,
}
firewallchain { 'INPUT:filter:IPv4':
purge  => true,
ignore => [
'-j fail2ban-', # ignore the fail2ban jump rule
],
}
firewallchain { 'fail2ban-sshd:filter:IPv4':
purge          => true,
ignore_foreign => true, # ignore not puppet managed rules in this chain
}
```
> **Note**: A additional `resources { 'firewall': purge => true }` is not allowed here in this case because `firewall` will else remove the normally …
> Force firewall chain delete

- manifests/linux/redhat.pp
Fix the SELinux contexts for CentOS Stream 8
and CentOS Stream 9.
> Fix SELinux context on newer CentOS

- lib/puppet/provider/firewall/ip6tables.rb
- spec/unit/puppet/provider/ip6tables_spec.rb
Facter is being asked for ip6tables_version every time ip6tables provider constructor is called during prefetch. This causes severe performance issues on systems with a lot of ip6tables rules (fe: openstack hypervisors) when even a single ipv6 rule is added. This commit should fix this.
> Change ip6tables_version to constant in provider.

- manifests/params.pp
disable firewalld for redhat 9
firewalld and iptables services conflict
> disable firewalld for RedHat 9

- README.md
> (maint) README typo fix

- lib/puppet/type/firewall.rb
Attributes currently are too limited and are causing errors with chains created by fail2ban.
> (GH-1156) Fix for jump/goto attributes

- lib/puppet/provider/firewall/firewall.rb
- spec/unit/puppet/provider/firewall/firewall_public_spec.rb
`dport/sport` values were being compared incorrectly when passed as integers or with multiple negated array values.
`state/ctstate/ctstatus` values were being compared incorrectly when multiple negated values are passed.
> (GH-1158) Fix for `dport/sport/state/ctstate/ctstatus` comparisons

- spec/acceptance/firewall_attributes_exceptions_spec.rb
- spec/acceptance/firewall_attributes_ipv6_exceptions_spec.rb
- spec/acceptance/firewall_attributes_ipv6_happy_path_spec.rb
- spec/acceptance/resource_cmd_spec.rb
- spec/spec_helper_acceptance_local.rb
- spec/unit/classes/firewall_linux_spec.rb
Removing EOL RedHat/Scientific/OracleLinux 6.
Add any additional context about the problem here. 
Mention any related issues or pull requests.
> [CAT-1425] : Removing RedHat/Scientific/OracleLinux 6

- lib/puppet/provider/firewall/firewall.rb
Common jump values, depending on the OS, can be returned either as upcase or downcase values causing idempotentcy issues. This had previously been dealt with by simply enforcing upcase on all passed values. However this caused issues when passing chain's as the jump target and so the code has been update to explicitly upcase the common values only.
Provide a detailed description of all the changes present in this pull request.
Add any additional context about the problem here. 
Mention any related issues or pull requests.
> (GH-1164) Only common jump values should be enforced as upcase

- README.md
- lib/puppet/type/firewall.rb
Couple of typo fixes in documentation.
> fix typos in documentation

- spec/acceptance/resource_cmd_spec.rb
While loading user profile, source command is not available for Ubuntu ARM which leads to spec failures.
> (CAT-1746) - Ubuntu ARM spec failure fixes

- lib/puppet/provider/firewallchain/firewallchain.rb
- spec/acceptance/firewallchain_spec.rb
- spec/unit/puppet/provider/firewallchain/firewallchain_spec.rb
Fixing the creation of firewall chai for IPv6 with nat table.
> (MODULES-11449) - Fix for IPv6 NAT chain

- lib/puppet/provider/firewallchain/firewallchain.rb
- spec/unit/puppet/provider/firewallchain/firewallchain_spec.rb
Fixes the issue when you are trying to create an in-built firewall chain in a table that was not been interacted with before. 
Currently if you are trying to create in-built chain in an empty table (nat, for example) puppet will apply manifest without actually doing anything every time you run it. This is because firewall module relyes on `iptables-save` output that will not contain in-built chain if corresponding table not been interacted with yet.
> Fix "creation" of empty built-in firewall chains

- lib/puppet_x/puppetlabs/firewall/utility.rb
This change should fix partial issue with resource generation:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/firewallchain: Could not autoload puppet/provider/firewallchain/firewallchain: no such file to load -- puppet_x/puppetlabs/firewall/ipcidr (file: /etc/puppetlabs/code/puppet-control/dev/profile_modules/profile/manifests/example/sample.pp, line: 40, column: 3) on node host.example.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```
You still need to do manual steps after upgrading from the previous version:
1. Find and delete firewall-related cache
`find $(puppet config print vardir) -ipath …
> Fix resource generation ipcidr dependency

- lib/puppet/provider/firewallchain/firewallchain.rb
This mirrors the values accepted for the firewall provider.
If a `firewallchain` resource is defined with `protocol => 'ip6tables'`, this fails with error `Execution of '' returned 1: Error: Could not execute posix command: no implicit conversion of nil into String`
> Support ip[6]tables protocol in firewallchain

- REFERENCE.md
- lib/puppet/type/firewall.rb
Fix for not rejecting valid iptables:
1. Allow -_ in ipset name
> (CAT-2088): Fix for not rejecting valid iptables

- REFERENCE.md
- lib/puppet/provider/firewall/firewall.rb
- lib/puppet/type/firewall.rb
- lib/puppet_x/puppetlabs/firewall/utility.rb
- spec/acceptance/firewall_attributes_exceptions_spec.rb
- spec/unit/puppet/provider/firewall/firewall_private_set_spec.rb
- spec/unit/puppet_x/puppetlabs/firewall/utility_spec.rb
Add ability to set match_mark|connmark as a mark/mask value
https://github.com/puppetlabs/puppetlabs-firewall/issues/1198
> (CAT-2088): Add ability to set match_mark|connmark as a mark/mask value

- lib/puppet/type/firewall.rb
Allow colon(:) in IP table syntax
> (CAT-2088): Allow colon(:) in IP table syntax

- REFERENCE.md
- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_attributes_happy_path_spec.rb
- spec/acceptance/firewall_attributes_ipv6_happy_path_spec.rb
Allows `--reject-with tcp-reset`.  This was allowed before the 7.0 rewrite, but lost and a regression introduced in that cutover.
`tcp-reset` is allowed (`man 8 iptables-extensions`) since ancient kernel 2.6.14, and is valid on TCP-matching rules.  There's no "you can only do this on TCP rules" limitation included in this PR, as it's valid to do (INPUT rule that matches TCP should jump to Xchain) -> (Xchain does a reject without declaring/knowing that it's TCP).
Resolves #1184
> Add `tcp-reset` as an allowed option for `--reject-with`

- lib/puppet/type/firewall.rb
- spec/acceptance/firewall_attributes_happy_path_spec.rb
- spec/unit/puppet/type/firewall_spec.rb
Allows a numeric port for `--to-ports` / `firewall.toports`
`Variant[Integer[0, 65535]` is Stdlib::Port, but using that fails with "firewall.toports references an unresolved type 'Stdlib::Port'" so oh well.
Resolves #1186
> Allow a singular numeric port for the `--to-ports` parameter

- lib/facter/iptables_persistent_version.rb
- spec/unit/facter/iptables_persistent_version_spec.rb
Update legacy facts with it respective counterpart
> (CAT-2215) Update legacy facts

- lib/puppet/provider/firewall/firewall.rb
- spec/acceptance/firewall_attributes_exceptions_spec.rb
- spec/unit/puppet/provider/firewall/firewall_public_spec.rb
If you set `dport|sport` values as a string with `-` as range indicator puppet will be applying manifest on every run.
> Port ranges as string with hyphen as range indicator should work

- lib/puppet/provider/firewallchain/firewallchain.rb
- spec/unit/puppet/provider/firewallchain/firewallchain_spec.rb
Fix non-idempotency of firewall table creation
The 'iptables-save' command behaves differently on rpm and deb based platforms.
rpm based: If an iptable has been interacted with, it will show up in the command even if it is empty.
deb based: If an iptable has been interacted with, it may not show up in the command if it is empty. If we add and then delete a rule, it shows up. But if we create the table using "iptables -N" it doesn't.
Specific tables always show up with "iptables -t #{table_name}".
Since, the tables are always already created and the module supports a specific set of them. This commit tries to check if they exist one by one using the "iptables -t" command.
Also, since the tables are being checked like this, all tables show up in the output, so adjusted the rpsec according …
> (MODULES-11476) Fix non-idempotency of firewall table creation
