puppetlabs/puppetlabs-firewall

README.markdown, lib/puppet/provider/firewall/ip6tables.rb, spec/acceptance/firewall_spec.rb
Rebase of puppetlabs/puppetlabs-firewall#467 with added tests and docs
Fixes puppetlabs/puppetlabs-firewall#467
=> MODULES-1612 - sync mask

spec/acceptance/firewall_spec.rb
=> QENG-1678 - Need to stop iptables to install ipset

lib/puppet/type/firewall.rb
Fixes user adding and removing using either UID or string username.
Tested with both negated and non-negated values and works on all
supported operating systems.
=> MODULES-753 further fixes

lib/facter/iptables_persistent_version.rb, lib/puppet/type/firewall.rb, lib/puppet/util/firewall.rb, manifests/params.pp, spec/unit/facter/iptables_persistent_version_spec.rb
Added support for Ubuntu 14.10.
=> Fix recent os

README.markdown
=> README: Added an example of an IPv6-based rule.

lib/puppet/provider/firewall/ip6tables.rb, lib/puppet/provider/firewall/iptables.rb, spec/acceptance/firewall_iptmodules_spec.rb
MODULES-1808 - Implemented code for resource map munging to allow a single ipt module to be used multiple times in a single rule
=> MODULES-1808 - Implemented code for resource map munging to allow a single ipt module to be used multiple times in a single rule

spec/acceptance/firewall_iptmodules_spec.rb
=> Fix iptmodules test

manifests/linux.pp, manifests/linux/gentoo.pp, manifests/params.pp, metadata.json, spec/unit/classes/firewall_linux_gentoo_spec.rb
=> MODULES-1832 - add Gentoo support

spec/acceptance/nodesets/centos-7-x64.yml, spec/acceptance/rhel7_spec.rb, spec/spec_helper_acceptance.rb
Lets us check the logic around making sure RHEL 7 changing service is working
=> (MAINT) Adds an acceptance test for RHEL 7

README.markdown
=> README: Added example of firewallchain for drop policy on input.

manifests/linux/redhat.pp
Fixed idempotency bug relating to MODULES-1984
=> Fixed idempotency bug relating to MODULES-1984

manifests/linux/redhat.pp
=> Fixed lint issue

manifests/params.pp, metadata.json, spec/unit/classes/firewall_linux_debian_spec.rb
Added iptables-persistent fix for Debian 8 and Ubuntu 14.10
=> Added iptables-persistent fix for Debian 8 and Ubuntu 14.10

README.markdown, lib/puppet/provider/firewall/ip6tables.rb, lib/puppet/provider/firewall/iptables.rb, lib/puppet/type/firewall.rb, spec/acceptance/firewall_mss_spec.rb, spec/acceptance/firewall_spec.rb
=> MSS feature

README.markdown, lib/puppet/provider/firewall/ip6tables.rb, lib/puppet/provider/firewall/iptables.rb, lib/puppet/type/firewall.rb, spec/acceptance/firewall_tee_spec.rb
=> Tee Support

README.markdown, lib/puppet/provider/firewall/ip6tables.rb, lib/puppet/provider/firewall/iptables.rb, lib/puppet/type/firewall.rb, spec/acceptance/match_mark_spec.rb, spec/fixtures/iptables/conversion_hash.rb
=> add match_mark

spec/acceptance/match_mark_spec.rb, spec/acceptance/params_spec.rb
=> Test fixes

lib/puppet/provider/firewall/ip6tables.rb, lib/puppet/provider/firewall/iptables.rb, lib/puppet/type/firewall.rb, spec/acceptance/firewall_mss_spec.rb, spec/fixtures/iptables/conversion_hash.rb
Add support for clamp-mss-to-pmtu
=> (MODULES-1766) Add support for clamp-mss-to-pmtu

README.markdown
Updated Readme for clamp_mss_to_pmtu
=> Updated Readme for clamp_mss_to_pmtu

CHANGELOG.md, README.markdown, metadata.json
=> 1.6.0 back to master

manifests/linux/redhat.pp, spec/acceptance/firewall_bridging_spec.rb, spec/acceptance/firewall_iptmodules_spec.rb, spec/acceptance/firewall_spec.rb, spec/acceptance/firewall_time_spec.rb, spec/acceptance/firewall_uid_spec.rb, spec/acceptance/firewallchain_spec.rb, spec/acceptance/invert_spec.rb, spec/acceptance/ip6_fragment_spec.rb, spec/acceptance/isfragment_spec.rb, spec/acceptance/purge_spec.rb, spec/acceptance/rules_spec.rb, spec/acceptance/socket_spec.rb, spec/acceptance/standard_usage_spec.rb
iptables-save always sets unconfined_u
=> Enforce the seluser on selinux systems

spec/acceptance/class_spec.rb, spec/acceptance/firewall_bridging_spec.rb, spec/acceptance/firewall_iptmodules_spec.rb, spec/acceptance/firewall_spec.rb, spec/acceptance/firewall_time_spec.rb, spec/acceptance/firewall_uid_spec.rb, spec/acceptance/firewallchain_spec.rb, spec/acceptance/invert_spec.rb, spec/acceptance/ip6_fragment_spec.rb, spec/acceptance/isfragment_spec.rb, spec/acceptance/purge_spec.rb, spec/acceptance/rules_spec.rb, spec/acceptance/standard_usage_spec.rb, spec/spec_helper_acceptance.rb
Only catch changes if not EL5 due to selinux warning issue.
=> Only catch changes if not EL5 due to selinux warning issue.

lib/puppet/type/firewall.rb, lib/puppet/type/firewallchain.rb
This will potentially solve a few corner cases.
=> Makes all the services autorequired by the firewall and firewallchain types.

spec/acceptance/rules_spec.rb
The aim is to keep the beaker connection happy...
=> Adding allow ssh rule to tests

spec/acceptance/firewall_clusterip_spec.rb
ipt module is causing system reboots.
=> (MAINT) - Commented out CLUSTERIP tests as there are suspicions that the

README.markdown, lib/puppet/provider/firewall/ip6tables.rb, lib/puppet/provider/firewall/iptables.rb, lib/puppet/type/firewall.rb, spec/acceptance/firewall_spec.rb
https://tickets.puppetlabs.com/browse/MODULES-2842
Added log-uid option. 
Ran into this "bug" during my testing as well since I was testing in an environment - https://tickets.puppetlabs.com/browse/PUP-731
=> Adding in log_uid boolean for LOG

README.markdown
I missed an arrow in the last pull request.
=> align arrows

spec/acceptance/nodesets/new/aio/debian-8-64mda.yml, spec/acceptance/nodesets/new/aio/redhat-6-64mda.yml, spec/acceptance/nodesets/new/aio/redhat-7-64mda.yml, spec/acceptance/nodesets/new/aio/ubuntu-1404-64mda.yml, spec/acceptance/nodesets/new/pe/centos-5-64mda.yml, spec/acceptance/nodesets/new/pe/centos-6-64mda.yml, spec/acceptance/nodesets/new/pe/centos-7-64mda.yml, spec/acceptance/nodesets/new/pe/debian-6-64mda.yml, spec/acceptance/nodesets/new/pe/debian-7-64mda.yml, spec/acceptance/nodesets/new/pe/debian-8-64mda.yml, spec/acceptance/nodesets/new/pe/oracle-6-64mda.yml, spec/acceptance/nodesets/new/pe/oracle-7-64mda.yml, spec/acceptance/nodesets/new/pe/redhat-5-64mda.yml, spec/acceptance/nodesets/new/pe/redhat-6-64mda.yml, spec/acceptance/nodesets/new/pe/redhat-7-64mda.yml, spec/acceptance/nodesets/new/pe/scientific-5-64mda.yml, spec/acceptance/nodesets/new/pe/scientific-6-64mda.yml, spec/acceptance/nodesets/new/pe/scientific-7-64mda.yml, spec/acceptance/nodesets/new/pe/sles-10-64mda.yml, spec/acceptance/nodesets/new/pe/sles-11-64mda.yml, spec/acceptance/nodesets/new/pe/sles-12-64mda.yml, spec/acceptance/nodesets/new/pe/ubuntu-1004-64mda.yml, spec/acceptance/nodesets/new/pe/ubuntu-1204-64mda.yml, spec/acceptance/nodesets/new/pe/ubuntu-1404-64mda.yml
=> (maint) re-add the local nodesets

spec/spec_helper_acceptance.rb
=> Prep 1.8.1

spec/acceptance/nodesets/new/aio/ubuntu-1604-64mda.yml, spec/acceptance/nodesets/new/pe/ubuntu-1604-64mda.yml
=> (QENG-3973) Adds Xenial nodesets for aio and pe

manifests/init.pp, metadata.json
This fix seems a little too easy to be all that's needed...
=> [#puppethack] MODULES-1222 - added containment

lib/puppet/type/firewall.rb, manifests/linux/redhat.pp
Caused through merge of PR's #658 and then subsequently this older PR #641
=> Fixes ip6tables errors on RHEL 6/7

CHANGELOG.md, metadata.json
Because of changing dependency on puppet to >= 4.0.0
=> Change from minor version bump to major version bump

Gemfile, README.markdown, lib/puppet/provider/firewall/ip6tables.rb, lib/puppet/provider/firewall/iptables.rb, lib/puppet/type/firewall.rb, spec/acceptance/firewall_bridging_spec.rb
Fixes MODULES-4234 (see https://tickets.puppetlabs.com/browse/MODULES-4234)
=> (MODULES-4234) Add support for --physdev-is-{in,out}

lib/puppet/provider/firewall/iptables.rb
The firewall module chockes on negated `--physdev-is...` rules:
... -m physdev ! --physdev-is-in ...
This PR fixes this.
This PR incorporates parts of #668, but handles all `--physdev-is-...` options, and also fixes a bug.
=> Properly handle negated `--physdev-is-...` rules

README.markdown, manifests/init.pp, manifests/linux.pp, spec/unit/classes/firewall_spec.rb, spec/unit/puppet/util/ipcidr_spec.rb
=> Allow managing ebtables

README.markdown, lib/puppet/type/firewall.rb
https://github.com/puppetlabs/puppetlabs-firewall/pull/722/ PR in question
=> Revert of PR 722 to undo the breaking changes introduced

lib/puppet/provider/firewall/iptables.rb
Debian 9 outputs multiple spaces.
=> (MODULES-5692) Match more than a single space

README.markdown
Clean up scattered references to this project so that docs make more
sense.
=>  (docs) Add some notes about firewall_multi

README.markdown
Tidied up the new section, made minor heading changes and edits.
=> clean up firewall_multi section, minor fixes

.gitignore, .pdkignore, .rubocop.yml, .travis.yml, Gemfile, Rakefile, metadata.json, spec/spec_helper.rb, spec/unit/puppet/type/firewallchain_spec.rb
pdk version: `1.7.0` 
pdk template ref: `1.7.0-0-g57412ed`
=> pdksync - Update using 1.7.0

README.markdown
The commit makes minor edits to the README
=> (MODULES-7804) - Minor README edits

README.markdown, lib/puppet/provider/firewall/iptables.rb, lib/puppet/type/firewall.rb, spec/acceptance/firewall_spec.rb, spec/fixtures/iptables/conversion_hash.rb, spec/unit/puppet/type/firewall_spec.rb
So it can be parsed when specified mutliple times, as well as being configured.
Perhaps acceptance tests are missing for it, I'll try add them soon.
=> (MODULES-8214) Handle src_type and dst_type as array

.gitattributes, .pdkignore, .travis.yml, Rakefile, metadata.json, spec/default_facts.yml, spec/spec_helper.rb
pdksync_heads/master-0-gbf720df
pdk version: `1.8.0`
=> pdksync - pdksync_heads/master-0-gbf720df

README.markdown, lib/puppet/provider/firewall/iptables.rb, lib/puppet/type/firewall.rb, spec/acceptance/firewall_attributes_happy_path_spec.rb
From my previous PR #828 , it appears that when a rule containing ipvs is applied it is not being saved properly. I have made some additional changes which fix this and also added the missing test.
=> (MODULES-8842) Fix ipvs not idempotent

metadata.json, provision.yaml
=> (FM-8673) - Support added for CentOS 8

.sync.yml, .travis.yml, metadata.json, spec/unit/documentation/readme_spec.rb
(maint) travis updates: bundler and slack
pdk version: `1.15.0`
=> pdksync - (maint) travis updates: bundler and slack

lib/puppet/provider/firewall/ip6tables.rb, lib/puppet/provider/firewall/iptables.rb, lib/puppet/type/firewall.rb
Adds the ability to specify iptables connection tracking helpers.
=> (MODULES-7800) Add the ability to specify iptables connection tracking helpers.

lib/puppet/util/firewall.rb
Use fact flush when available as this will fix compatibility with Facter 4
=> (maint) Use fact.flush only when available

lib/puppet/provider/firewall/ip6tables.rb, lib/puppet/provider/firewall/iptables.rb, lib/puppet/type/firewall.rb, spec/acceptance/firewall_attributes_happy_path_spec.rb, spec/fixtures/iptables/conversion_hash.rb, spec/spec_helper_acceptance_local.rb
=> Add acceptance and unit test

manifests/init.pp, manifests/linux.pp, manifests/linux/archlinux.pp, manifests/linux/debian.pp, manifests/linux/gentoo.pp, manifests/linux/redhat.pp, manifests/params.pp
=> Resolve puppet-lint notices

.sync.yml, .travis.yml, provision.yaml, spec/acceptance/firewall_attributes_exceptions_spec.rb, spec/acceptance/firewall_attributes_ipv6_exceptions_spec.rb, spec/acceptance/resource_cmd_spec.rb, spec/spec_helper_acceptance_local.rb
The problem was found on commit https://github.com/puppetlabs/puppetlabs-firewall/pull/926/commits/58f95fc6c3d7ea55531962442b93c5026943abbd - Implement CentOS 8 travis tests.
The `--hashlimit-htable-size` value lower than `1048576` because the value of `HASHLIMIT_MAX_SIZE` is 1048576.
https://github.com/torvalds/linux/blob/418baf2c28f3473039f2f7377760bd8f6897ae18/net/netfilter/xt_hashlimit.c#L836
=> (IAC-894) - change hashlimit_htable_size to a lower value

.sync.yml, .travis.yml, metadata.json
=> (pdksync) - implement centos 8 on travis

.github/workflows/nightly.yml, .github/workflows/pr_test.yml, .rubocop.yml, .travis.yml, Rakefile, lib/puppet/provider/firewall/iptables.rb, metadata.json
Update gha templates
pdk version: `1.19.0.pre (47)`
=> pdksync - Update gha templates

.github/workflows/nightly.yml, .github/workflows/pr_test.yml
I am aware this change will be consumed on the next pdk update, however the #980 containing this is outstanding with issues. Putting the change directly in to unblock the completion of this piece of work. https://github.com/puppetlabs/puppet_litmus/issues/380
=> (GH-380) - Litmus, move inventory location

lib/puppet/type/firewall.rb, metadata.json, spec/acceptance/firewall_attributes_ipv6_happy_path_spec.rb
(IAC-1709) - Add Support for Debian 11
pdk version: `2.1.1`
=> pdksync - (IAC-1709) - Add Support for Debian 11

manifests/linux.pp, metadata.json, spec/spec_helper_acceptance_local.rb, spec/unit/classes/firewall_linux_debian_spec.rb, spec/unit/classes/firewall_linux_redhat_spec.rb, spec/unit/classes/firewall_linux_spec.rb
This is a follow-up to #1008 which fix CI.
Closes: #1008
=> (IAC-1739) Fix CI with stdlib 8.0.0

.github/workflows/auto_release.yml, .sync.yml, Rakefile, metadata.json
=> pdksync: changelog_max_issues set to 500

lib/puppet/type/firewall.rb
See https://tickets.puppetlabs.com/browse/MODULES-11203
=> Bugfix MODULES-11203: error on second apply when uid or gid is specified as a range

.devcontainer/README.md, .devcontainer/devcontainer.json, .github/workflows/auto_release.yml, .github/workflows/spec.yml, .rubocop.yml, Gemfile, metadata.json
pdksync_heads/main-0-gf3911d3
pdk version: `2.3.0`
=> pdksync - pdksync_heads/main-0-gf3911d3

.github/workflows/spec.yml, .puppet-lint.rc, .sync.yml, Rakefile, lib/puppet/provider/firewallchain/iptables_chain.rb, lib/puppet/type/firewall.rb, lib/puppet/util/firewall.rb, manifests/linux.pp, metadata.json
(Maint) PDK Update
pdk version: `2.3.0`
=> pdksync - (Maint) PDK Update

manifests/linux/redhat.pp, manifests/params.pp, metadata.json, spec/acceptance/firewall_attributes_exceptions_spec.rb, spec/acceptance/firewall_attributes_ipv6_exceptions_spec.rb, spec/acceptance/firewall_attributes_ipv6_happy_path_spec.rb
(GH-cat-12) Add Support for Redhat 9
pdk version: `2.4.0`
=> pdksync - (GH-cat-12) Add Support for Redhat 9

CHANGELOG.md, metadata.json
=> Release prep v3.6.0

.puppet-lint.rc, .sync.yml, Rakefile, manifests/init.pp, manifests/linux.pp, manifests/linux/archlinux.pp, manifests/linux/debian.pp, manifests/linux/gentoo.pp, manifests/linux/redhat.pp, manifests/params.pp, spec/spec_helper_local.rb, spec/unit/classes/firewall_linux_archlinux_spec.rb, spec/unit/classes/firewall_linux_debian_spec.rb, spec/unit/classes/firewall_linux_redhat_spec.rb, spec/unit/classes/firewall_linux_spec.rb
Code now compliant with rules regarding:
legacy facts
top scope facts
relative classname inclusion
parameter datatypes
=> (CONT-352) Syntax update

manifests/linux/debian.pp, manifests/linux/redhat.pp, metadata.json
(MAINT) - Update Stdlib dependency
pdk version: `2.7.1`
=> pdksync - (MAINT) - Allow Stdlib 9.x

README.md
Provide a detailed description of all the changes present in this pull request.
Add any additional context about the problem here. 
Mention any related issues or pull requests.
=> (maint) Update all README.md mentions of `action` to `jump`

README.md
Provide a detailed description of all the changes present in this pull request.
Add any additional context about the problem here. 
Mention any related issues or pull requests.
=> (maint) README.md typo fix
